resource "google_bigquery_table" "fact_earthquakes" {
  dataset_id = "dbt_andy_nelson"
  project    = var.project
  schema     = "[{\"name\":\"feature_type\",\"type\":\"STRING\"},{\"name\":\"id\",\"type\":\"STRING\"},{\"name\":\"magnitude\",\"type\":\"FLOAT\"},{\"name\":\"place\",\"type\":\"STRING\"},{\"name\":\"origin_timestamp\",\"type\":\"INTEGER\"},{\"name\":\"updated_timestamp\",\"type\":\"INTEGER\"},{\"name\":\"timezone_offset\",\"type\":\"INTEGER\"},{\"name\":\"url_link\",\"type\":\"STRING\"},{\"name\":\"properties_detail\",\"type\":\"STRING\"},{\"name\":\"felt_submissions\",\"type\":\"INTEGER\"},{\"name\":\"cdi_inensity\",\"type\":\"INTEGER\"},{\"name\":\"maximum_instrumental_intensity\",\"type\":\"FLOAT\"},{\"name\":\"alert\",\"type\":\"STRING\"},{\"name\":\"status\",\"type\":\"STRING\"},{\"name\":\"tsunami\",\"type\":\"INTEGER\"},{\"name\":\"significant_number\",\"type\":\"INTEGER\"},{\"name\":\"network_id\",\"type\":\"STRING\"},{\"name\":\"properties_code\",\"type\":\"STRING\"},{\"name\":\"properties_ids\",\"type\":\"STRING\"},{\"name\":\"properties_sources\",\"type\":\"STRING\"},{\"name\":\"properties_types\",\"type\":\"STRING\"},{\"name\":\"number_stations_total\",\"type\":\"FLOAT\"},{\"name\":\"minimum_horizontal_distance_to_station\",\"type\":\"FLOAT\"},{\"name\":\"root_mean_square_travel_time\",\"type\":\"FLOAT\"},{\"name\":\"gap_between_stations\",\"type\":\"FLOAT\"},{\"name\":\"magType\",\"type\":\"STRING\"},{\"name\":\"properties_type\",\"type\":\"STRING\"},{\"name\":\"properties_title\",\"type\":\"STRING\"},{\"name\":\"geometry_type\",\"type\":\"STRING\"},{\"fields\":[{\"fields\":[{\"name\":\"item\",\"type\":\"FLOAT\"}],\"mode\":\"REPEATED\",\"name\":\"list\",\"type\":\"RECORD\"}],\"name\":\"geometry_coordinates\",\"type\":\"RECORD\"},{\"name\":\"generated\",\"type\":\"INTEGER\"},{\"name\":\"url_string\",\"type\":\"STRING\"},{\"name\":\"title\",\"type\":\"STRING\"},{\"name\":\"review_status\",\"type\":\"INTEGER\"},{\"name\":\"api\",\"type\":\"STRING\"},{\"name\":\"count\",\"type\":\"INTEGER\"},{\"name\":\"geometry_coordinates_longitude\",\"type\":\"FLOAT\"},{\"name\":\"geometry_coordinates_latitude\",\"type\":\"FLOAT\"},{\"name\":\"earthquake_depth\",\"type\":\"FLOAT\"},{\"name\":\"properties_time_datetime\",\"type\":\"TIMESTAMP\"},{\"name\":\"properties_updated_datetime\",\"type\":\"TIMESTAMP\"},{\"name\":\"metadata_generated_datetime\",\"type\":\"TIMESTAMP\"},{\"name\":\"dataframe_timestamp_now\",\"type\":\"TIMESTAMP\"},{\"name\":\"rn\",\"type\":\"INTEGER\"}]"
  table_id   = "fact_earthquakes"

  time_partitioning {
    field = "properties_time_datetime"
    type  = "DAY"
  }
}

