resource "google_bigquery_table" "stg_earthquakes" {
  dataset_id = "dbt_andy_nelson"
  project    = var.project
  schema     = "[{\"name\":\"feature_type\",\"type\":\"STRING\"},{\"name\":\"id\",\"type\":\"STRING\"},{\"name\":\"magnitude\",\"type\":\"FLOAT\"},{\"name\":\"place\",\"type\":\"STRING\"},{\"name\":\"origin_timestamp\",\"type\":\"INTEGER\"},{\"name\":\"updated_timestamp\",\"type\":\"INTEGER\"},{\"name\":\"timezone_offset\",\"type\":\"INTEGER\"},{\"name\":\"url_link\",\"type\":\"STRING\"},{\"name\":\"properties_detail\",\"type\":\"STRING\"},{\"name\":\"felt_submissions\",\"type\":\"INTEGER\"},{\"name\":\"cdi_inensity\",\"type\":\"INTEGER\"},{\"name\":\"maximum_instrumental_intensity\",\"type\":\"FLOAT\"},{\"name\":\"alert\",\"type\":\"STRING\"},{\"name\":\"status\",\"type\":\"STRING\"},{\"name\":\"tsunami\",\"type\":\"INTEGER\"},{\"name\":\"significant_number\",\"type\":\"INTEGER\"},{\"name\":\"network_id\",\"type\":\"STRING\"},{\"name\":\"properties_code\",\"type\":\"STRING\"},{\"name\":\"properties_ids\",\"type\":\"STRING\"},{\"name\":\"properties_sources\",\"type\":\"STRING\"},{\"name\":\"properties_types\",\"type\":\"STRING\"},{\"name\":\"number_stations_total\",\"type\":\"FLOAT\"},{\"name\":\"minimum_horizontal_distance_to_station\",\"type\":\"FLOAT\"},{\"name\":\"root_mean_square_travel_time\",\"type\":\"FLOAT\"},{\"name\":\"gap_between_stations\",\"type\":\"FLOAT\"},{\"name\":\"magType\",\"type\":\"STRING\"},{\"name\":\"properties_type\",\"type\":\"STRING\"},{\"name\":\"properties_title\",\"type\":\"STRING\"},{\"name\":\"geometry_type\",\"type\":\"STRING\"},{\"fields\":[{\"fields\":[{\"name\":\"item\",\"type\":\"FLOAT\"}],\"mode\":\"REPEATED\",\"name\":\"list\",\"type\":\"RECORD\"}],\"name\":\"geometry_coordinates\",\"type\":\"RECORD\"},{\"name\":\"generated\",\"type\":\"INTEGER\"},{\"name\":\"url_string\",\"type\":\"STRING\"},{\"name\":\"title\",\"type\":\"STRING\"},{\"name\":\"review_status\",\"type\":\"INTEGER\"},{\"name\":\"api\",\"type\":\"STRING\"},{\"name\":\"count\",\"type\":\"INTEGER\"},{\"name\":\"geometry_coordinates_longitude\",\"type\":\"FLOAT\"},{\"name\":\"geometry_coordinates_latitude\",\"type\":\"FLOAT\"},{\"name\":\"earthquake_depth\",\"type\":\"FLOAT\"},{\"name\":\"properties_time_datetime\",\"type\":\"TIMESTAMP\"},{\"name\":\"properties_updated_datetime\",\"type\":\"TIMESTAMP\"},{\"name\":\"metadata_generated_datetime\",\"type\":\"TIMESTAMP\"},{\"name\":\"dataframe_timestamp_now\",\"type\":\"TIMESTAMP\"},{\"name\":\"rn\",\"type\":\"INTEGER\"}]"
  table_id   = "stg_earthquakes"

  view {
    query          = "with earthquakes as \n(\n    select *,\n        row_number() over(partition by id, properties_updated_datetime) as rn\n    from `YOUR-PROJECT-123456`.`raw_usgs_earthquakes`.`raw_earthquakes`\n    where id is not null \n)\nselect \n    cast(type as STRING) as feature_type,\n    cast(id as STRING) as id,\n    cast(properties_mag as FLOAT64) as magnitude,\n    cast(properties_place as STRING) as place,\n    cast(properties_time as INTEGER) as origin_timestamp,\n    cast(properties_updated as INTEGER) as updated_timestamp,\n    cast(properties_tz as INTEGER) as timezone_offset,\n    cast(properties_url as STRING) as url_link,\n    cast(properties_detail as STRING) as properties_detail,\n    cast(properties_felt as INTEGER) as felt_submissions,\n    cast(properties_cdi as INTEGER) as cdi_inensity,\n    cast(properties_mmi as FLOAT64) as maximum_instrumental_intensity,\n    cast(properties_alert as STRING) as alert,\n    cast(properties_status as STRING) as status,\n    cast(properties_tsunami as INTEGER) as tsunami,\n    cast(properties_sig as INTEGER) as significant_number,\n    cast(properties_net as STRING) as network_id,\n    cast(properties_code as STRING) as properties_code,\n    cast(properties_ids as STRING) as properties_ids,\n    cast(properties_sources as STRING) as properties_sources,\n    cast(properties_types as STRING) as properties_types,\n    cast(properties_nst as FLOAT64) as number_stations_total,\n    cast(properties_dmin as FLOAT64) as minimum_horizontal_distance_to_station,\n    cast(properties_rms as FLOAT64) as root_mean_square_travel_time,\n    cast(properties_gap as FLOAT64) as  gap_between_stations,\n    cast(properties_magType as STRING) as magType,\n    cast(properties_type as STRING) as properties_type,\n    cast(properties_title as STRING) as properties_title,\n    cast(geometry_type as STRING) as geometry_type,\n    geometry_coordinates as geometry_coordinates,\n    cast(generated as INTEGER) as generated,\n    cast(url as STRING) as url_string,\n    cast(title as STRING) as title,\n    cast(status as INTEGER) as review_status,\n    cast(api as STRING) as api,\n    cast(count as INTEGER) as count,\n    cast(geometry_coordinates_longitude as FLOAT64) as geometry_coordinates_longitude,\n    cast(geometry_coordinates_latitude as FLOAT64) as geometry_coordinates_latitude,\n    cast(geometry_coordinates_depth as FLOAT64) as earthquake_depth,\n    cast(properties_time_datetime as TIMESTAMP) as properties_time_datetime,\n    cast(properties_updated_datetime as TIMESTAMP) as properties_updated_datetime,\n    cast(metadata_generated_datetime as TIMESTAMP) as metadata_generated_datetime,\n    cast(dataframe_timestamp_now as TIMESTAMP) as dataframe_timestamp_now,\n    cast(rn as INTEGER) as rn\nfrom earthquakes \nwhere rn = 1"
    use_legacy_sql = false
  }
}
# terraform import google_bigquery_table.stg_earthquakes projects/YOUR-PROJECT-123456/datasets/dbt_andy_nelson/tables/stg_earthquakes
